version: '3.9'

services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: notesstack_backend:latest
    environment:
      - MONGO_URI=notesstack_mongo://mongo:27017
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  frontend:
    image: notesstack_frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

volumes:
  - mongo-data: {}

networks:
  app-network:
    driver: overlay